version: '3.9'
services:
    projtracktor:
        build: .
        ports:
            - $PORT:$PORT # HOST:CONTAINER
        volumes:
            - .:/app/
        environment:
            - PORT=$PORT
        command: npm run start:dev
        depends_on:
            - db
        networks:
            - projtracktor-network

    db:
        image: postgres
        ports:
            - $DB_PORT:5432
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_NAME
        networks:
            - projtracktor-network

networks:
    projtracktor-network:
