version: '3.9'
services:
    projtracktor:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - .:/app/
        environment:
            - PORT=$PORT
        command: npm run start:dev
        depends_on:
            - db
        networks:
            - projtracktor-network

    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_NAME
        networks:
            - projtracktor-network

networks:
    projtracktor-network:
